name: CI/CD Pipeline

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  test-cases:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python for running tests
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover tests


  build-and-publish:
    runs-on: ubuntu-latest
    needs: test-cases
    steps:

      - name: Checkout repository-helmcharts
        uses: actions/checkout@v4
        with:
          path: helmcharts

      - name: Checkout repository
        uses: actions/checkout@v4
      
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: run-python-script
        run: /
          python ./helmcharts/script.py ${{ github.run_id }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-flask-app:${{ github.run_id }} .

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-app:${{ github.run_id }}
      
      - name: push-code-helmchart
        run: /
          cd helmcharts
          git add .
          git commit -m "added image tag ${{ github.run_id }}"
          
    

